# id -> project dict
PROJECTS = {
    "leaky_faucet": {
        "name": "Fix a Leaky Faucet",
        "category": "Plumbing",
        "difficulty": "Easy",
        "est_time_hours": 1,
        "tools": ["Adjustable wrench", "Screwdriver set", "Plumber's tape"],
        "materials": [
            {"name": "Faucet cartridge/washer kit", "qty": 1, "unit": "kit", "est_price": 12.00},
            {"name": "Plumber's grease", "qty": 1, "unit": "tube", "est_price": 5.50},
        ],
    },
    "running_toilet": {
        "name": "Fix a Running Toilet",
        "category": "Plumbing",
        "difficulty": "Easy",
        "est_time_hours": 1,
        "tools": ["Adjustable wrench", "Sponge"],
        "materials": [
            {"name": "Toilet fill valve", "qty": 1, "unit": "each", "est_price": 15.00},
            {"name": "Toilet flapper", "qty": 1, "unit": "each", "est_price": 8.00},
        ],
    },
    "replace_toilet": {
        "name": "Replace a Toilet",
        "category": "Plumbing",
        "difficulty": "Moderate",
        "est_time_hours": 3,
        "tools": ["Adjustable wrench", "Putty knife", "Level", "Bucket", "Sponge"],
        "materials": [
            {"name": "Toilet (bowl + tank kit)", "qty": 1, "unit": "each", "est_price": 180.00},
            {"name": "Wax ring with flange", "qty": 1, "unit": "each", "est_price": 7.00},
            {"name": "Toilet bolts/cap kit", "qty": 1, "unit": "kit", "est_price": 6.00},
            {"name": "Braided supply line", "qty": 1, "unit": "each", "est_price": 9.00},
        ],
    },
    "patch_drywall": {
        "name": "Patch a Drywall Hole",
        "category": "Walls & Ceilings",
        "difficulty": "Easy",
        "est_time_hours": 2,
        "tools": ["Putty knife", "Sanding block", "Utility knife"],
        "materials": [
            {"name": "Drywall patch kit (self-adhesive)", "qty": 1, "unit": "kit", "est_price": 9.00},
            {"name": "Spackling/joint compound", "qty": 1, "unit": "quart", "est_price": 7.50},
            {"name": "Sandpaper (medium grit)", "qty": 1, "unit": "pack", "est_price": 6.00},
            {"name": "Touch-up paint", "qty": 1, "unit": "pint", "est_price": 8.00},
        ],
    },
    "paint_room": {
        "name": "Paint a Room",
        "category": "Painting",
        "difficulty": "Easy",
        "est_time_hours": 6,
        "tools": ["Paint roller frame", "Paint tray", "Painter's tape (tool)", "Drop cloth", "Ladder"],
        "materials": [
            {"name": "Interior paint (gallon)", "qty": 2, "unit": "gallon", "est_price": 32.00},
            {"name": "Primer (gallon)", "qty": 1, "unit": "gallon", "est_price": 25.00},
            {"name": "Roller covers (2-pack)", "qty": 1, "unit": "pack", "est_price": 6.00},
            {"name": "Angled paint brush 2.5in", "qty": 1, "unit": "each", "est_price": 7.00},
            {"name": "Painter's tape roll", "qty": 2, "unit": "roll", "est_price": 5.00},
            {"name": "Plastic drop cloth", "qty": 1, "unit": "each", "est_price": 8.00},
        ],
    },
    "install_ceiling_fan": {
        "name": "Install a Ceiling Fan",
        "category": "Electrical",
        "difficulty": "Moderate",
        "est_time_hours": 3,
        "tools": ["Screwdriver set", "Voltage tester", "Wire strippers", "Ladder", "Drill/driver"],
        "materials": [
            {"name": "Ceiling fan (with light kit)", "qty": 1, "unit": "each", "est_price": 90.00},
            {"name": "Ceiling fan rated electrical box", "qty": 1, "unit": "each", "est_price": 12.00},
            {"name": "Wire nuts (assorted pack)", "qty": 1, "unit": "pack", "est_price": 5.00},
        ],
    },
    "install_light_fixture": {
        "name": "Install a Light Fixture",
        "category": "Electrical",
        "difficulty": "Easy",
        "est_time_hours": 1,
        "tools": ["Screwdriver set", "Voltage tester", "Wire strippers", "Ladder"],
        "materials": [
            {"name": "Light fixture", "qty": 1, "unit": "each", "est_price": 45.00},
            {"name": "Wire nuts (assorted pack)", "qty": 1, "unit": "pack", "est_price": 5.00},
        ],
    },
    "hang_shelf": {
        "name": "Hang a Shelf",
        "category": "Carpentry",
        "difficulty": "Easy",
        "est_time_hours": 1,
        "tools": ["Drill/driver", "Level", "Stud finder", "Tape measure", "Pencil"],
        "materials": [
            {"name": "Shelf board", "qty": 1, "unit": "each", "est_price": 20.00},
            {"name": "Shelf brackets (pair)", "qty": 1, "unit": "pair", "est_price": 10.00},
            {"name": "Wall anchors (pack)", "qty": 1, "unit": "pack", "est_price": 4.50},
            {"name": "Wood screws (assorted, box)", "qty": 1, "unit": "box", "est_price": 6.00},
        ],
    },
    "weatherproof_windows": {
        "name": "Weatherproof Windows & Doors",
        "category": "Energy Efficiency",
        "difficulty": "Easy",
        "est_time_hours": 2,
        "tools": ["Utility knife", "Caulk gun", "Tape measure"],
        "materials": [
            {"name": "Weatherstripping roll", "qty": 2, "unit": "roll", "est_price": 8.00},
            {"name": "Door sweep", "qty": 1, "unit": "each", "est_price": 12.00},
            {"name": "Exterior caulk tube", "qty": 2, "unit": "tube", "est_price": 6.00},
        ],
    },
    "raised_garden_bed": {
        "name": "Build a Raised Garden Bed",
        "category": "Outdoor",
        "difficulty": "Moderate",
        "est_time_hours": 4,
        "tools": ["Circular saw", "Drill/driver", "Tape measure", "Level", "Square"],
        "materials": [
            {"name": "Cedar boards (2x6x8)", "qty": 6, "unit": "each", "est_price": 14.00},
            {"name": "Corner brackets (4-pack)", "qty": 1, "unit": "pack", "est_price": 15.00},
            {"name": "Exterior wood screws (box)", "qty": 1, "unit": "box", "est_price": 9.00},
            {"name": "Garden soil (bag)", "qty": 6, "unit": "bag", "est_price": 5.00},
            {"name": "Landscape fabric", "qty": 1, "unit": "roll", "est_price": 15.00},
        ],
    },
    "deck_board_repair": {
        "name": "Repair Damaged Deck Boards",
        "category": "Outdoor",
        "difficulty": "Moderate",
        "est_time_hours": 3,
        "tools": ["Circular saw", "Drill/driver", "Pry bar", "Tape measure", "Safety glasses"],
        "materials": [
            {"name": "Pressure-treated deck board", "qty": 3, "unit": "each", "est_price": 18.00},
            {"name": "Deck screws (box)", "qty": 1, "unit": "box", "est_price": 11.00},
            {"name": "Wood sealant", "qty": 1, "unit": "quart", "est_price": 14.00},
        ],
    },
    "install_dimmer_switch": {
        "name": "Install a Dimmer Switch",
        "category": "Electrical",
        "difficulty": "Easy",
        "est_time_hours": 1,
        "tools": ["Screwdriver set", "Voltage tester", "Wire strippers"],
        "materials": [
            {"name": "Dimmer switch", "qty": 1, "unit": "each", "est_price": 18.00},
            {"name": "Wire nuts (assorted pack)", "qty": 1, "unit": "pack", "est_price": 5.00},
            {"name": "Switch wall plate", "qty": 1, "unit": "each", "est_price": 3.00},
        ],
    },
}
